- name: Build EXE with PyInstaller
        run: |
          pip install customtkinter
          pyinstaller --onefile --windowed --uac-admin --collect-data pydivert --collect-all customtkinter main.py
